// Code generated by MockGen. DO NOT EDIT.
// Source: internal/dao/interfaces/semantic.go
//
// Generated by this command:
//
//	mockgen -source=internal/dao/interfaces/semantic.go -destination=internal/testutil/mocks/mock_semantic_dao.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	entity "robot_scheduler/internal/model/entity"

	gomock "go.uber.org/mock/gomock"
)

// MockSemanticMapDAO is a mock of SemanticMapDAO interface.
type MockSemanticMapDAO struct {
	ctrl     *gomock.Controller
	recorder *MockSemanticMapDAOMockRecorder
	isgomock struct{}
}

// MockSemanticMapDAOMockRecorder is the mock recorder for MockSemanticMapDAO.
type MockSemanticMapDAOMockRecorder struct {
	mock *MockSemanticMapDAO
}

// NewMockSemanticMapDAO creates a new mock instance.
func NewMockSemanticMapDAO(ctrl *gomock.Controller) *MockSemanticMapDAO {
	mock := &MockSemanticMapDAO{ctrl: ctrl}
	mock.recorder = &MockSemanticMapDAOMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSemanticMapDAO) EXPECT() *MockSemanticMapDAOMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockSemanticMapDAO) Create(ctx context.Context, semanticMap *entity.SemanticMap) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, semanticMap)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockSemanticMapDAOMockRecorder) Create(ctx, semanticMap any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockSemanticMapDAO)(nil).Create), ctx, semanticMap)
}

// Delete mocks base method.
func (m *MockSemanticMapDAO) Delete(ctx context.Context, id uint) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockSemanticMapDAOMockRecorder) Delete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockSemanticMapDAO)(nil).Delete), ctx, id)
}

// FindAll mocks base method.
func (m *MockSemanticMapDAO) FindAll(ctx context.Context) ([]*entity.SemanticMap, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindAll", ctx)
	ret0, _ := ret[0].([]*entity.SemanticMap)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindAll indicates an expected call of FindAll.
func (mr *MockSemanticMapDAOMockRecorder) FindAll(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindAll", reflect.TypeOf((*MockSemanticMapDAO)(nil).FindAll), ctx)
}

// FindByID mocks base method.
func (m *MockSemanticMapDAO) FindByID(ctx context.Context, id uint) (*entity.SemanticMap, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByID", ctx, id)
	ret0, _ := ret[0].(*entity.SemanticMap)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByID indicates an expected call of FindByID.
func (mr *MockSemanticMapDAOMockRecorder) FindByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByID", reflect.TypeOf((*MockSemanticMapDAO)(nil).FindByID), ctx, id)
}

// FindPage mocks base method.
func (m *MockSemanticMapDAO) FindPage(ctx context.Context, offset, limit int) ([]*entity.SemanticMap, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindPage", ctx, offset, limit)
	ret0, _ := ret[0].([]*entity.SemanticMap)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// FindPage indicates an expected call of FindPage.
func (mr *MockSemanticMapDAOMockRecorder) FindPage(ctx, offset, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindPage", reflect.TypeOf((*MockSemanticMapDAO)(nil).FindPage), ctx, offset, limit)
}

// Update mocks base method.
func (m *MockSemanticMapDAO) Update(ctx context.Context, semanticMap *entity.SemanticMap) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, semanticMap)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockSemanticMapDAOMockRecorder) Update(ctx, semanticMap any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockSemanticMapDAO)(nil).Update), ctx, semanticMap)
}
