// Code generated by MockGen. DO NOT EDIT.
// Source: internal/dao/interfaces/user_operation.go
//
// Generated by this command:
//
//	mockgen -source=internal/dao/interfaces/user_operation.go -destination=internal/testutil/mocks/mock_user_operation_dao.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	entity "robot_scheduler/internal/model/entity"

	gomock "go.uber.org/mock/gomock"
)

// MockUserOperationDAO is a mock of UserOperationDAO interface.
type MockUserOperationDAO struct {
	ctrl     *gomock.Controller
	recorder *MockUserOperationDAOMockRecorder
	isgomock struct{}
}

// MockUserOperationDAOMockRecorder is the mock recorder for MockUserOperationDAO.
type MockUserOperationDAOMockRecorder struct {
	mock *MockUserOperationDAO
}

// NewMockUserOperationDAO creates a new mock instance.
func NewMockUserOperationDAO(ctrl *gomock.Controller) *MockUserOperationDAO {
	mock := &MockUserOperationDAO{ctrl: ctrl}
	mock.recorder = &MockUserOperationDAOMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserOperationDAO) EXPECT() *MockUserOperationDAOMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockUserOperationDAO) Create(ctx context.Context, operation *entity.UserOperation) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, operation)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockUserOperationDAOMockRecorder) Create(ctx, operation any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockUserOperationDAO)(nil).Create), ctx, operation)
}

// Delete mocks base method.
func (m *MockUserOperationDAO) Delete(ctx context.Context, id uint) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockUserOperationDAOMockRecorder) Delete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockUserOperationDAO)(nil).Delete), ctx, id)
}

// FindAll mocks base method.
func (m *MockUserOperationDAO) FindAll(ctx context.Context) ([]*entity.UserOperation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindAll", ctx)
	ret0, _ := ret[0].([]*entity.UserOperation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindAll indicates an expected call of FindAll.
func (mr *MockUserOperationDAOMockRecorder) FindAll(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindAll", reflect.TypeOf((*MockUserOperationDAO)(nil).FindAll), ctx)
}

// FindByID mocks base method.
func (m *MockUserOperationDAO) FindByID(ctx context.Context, id uint) (*entity.UserOperation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByID", ctx, id)
	ret0, _ := ret[0].(*entity.UserOperation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByID indicates an expected call of FindByID.
func (mr *MockUserOperationDAOMockRecorder) FindByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByID", reflect.TypeOf((*MockUserOperationDAO)(nil).FindByID), ctx, id)
}

// FindPage mocks base method.
func (m *MockUserOperationDAO) FindPage(ctx context.Context, offset, limit int) ([]*entity.UserOperation, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindPage", ctx, offset, limit)
	ret0, _ := ret[0].([]*entity.UserOperation)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// FindPage indicates an expected call of FindPage.
func (mr *MockUserOperationDAOMockRecorder) FindPage(ctx, offset, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindPage", reflect.TypeOf((*MockUserOperationDAO)(nil).FindPage), ctx, offset, limit)
}

// Update mocks base method.
func (m *MockUserOperationDAO) Update(ctx context.Context, operation *entity.UserOperation) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, operation)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockUserOperationDAOMockRecorder) Update(ctx, operation any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockUserOperationDAO)(nil).Update), ctx, operation)
}
