// Code generated by MockGen. DO NOT EDIT.
// Source: internal/dao/interfaces/device.go
//
// Generated by this command:
//
//	mockgen -source=internal/dao/interfaces/device.go -destination=internal/testutil/mocks/mock_device_dao.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	entity "robot_scheduler/internal/model/entity"

	gomock "go.uber.org/mock/gomock"
)

// MockDeviceDAO is a mock of DeviceDAO interface.
type MockDeviceDAO struct {
	ctrl     *gomock.Controller
	recorder *MockDeviceDAOMockRecorder
	isgomock struct{}
}

// MockDeviceDAOMockRecorder is the mock recorder for MockDeviceDAO.
type MockDeviceDAOMockRecorder struct {
	mock *MockDeviceDAO
}

// NewMockDeviceDAO creates a new mock instance.
func NewMockDeviceDAO(ctrl *gomock.Controller) *MockDeviceDAO {
	mock := &MockDeviceDAO{ctrl: ctrl}
	mock.recorder = &MockDeviceDAOMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDeviceDAO) EXPECT() *MockDeviceDAOMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockDeviceDAO) Create(ctx context.Context, device *entity.Device) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, device)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockDeviceDAOMockRecorder) Create(ctx, device any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockDeviceDAO)(nil).Create), ctx, device)
}

// Delete mocks base method.
func (m *MockDeviceDAO) Delete(ctx context.Context, id uint) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockDeviceDAOMockRecorder) Delete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockDeviceDAO)(nil).Delete), ctx, id)
}

// FindAll mocks base method.
func (m *MockDeviceDAO) FindAll(ctx context.Context) ([]*entity.Device, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindAll", ctx)
	ret0, _ := ret[0].([]*entity.Device)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindAll indicates an expected call of FindAll.
func (mr *MockDeviceDAOMockRecorder) FindAll(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindAll", reflect.TypeOf((*MockDeviceDAO)(nil).FindAll), ctx)
}

// FindByID mocks base method.
func (m *MockDeviceDAO) FindByID(ctx context.Context, id uint) (*entity.Device, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByID", ctx, id)
	ret0, _ := ret[0].(*entity.Device)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByID indicates an expected call of FindByID.
func (mr *MockDeviceDAOMockRecorder) FindByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByID", reflect.TypeOf((*MockDeviceDAO)(nil).FindByID), ctx, id)
}

// FindPage mocks base method.
func (m *MockDeviceDAO) FindPage(ctx context.Context, offset, limit int) ([]*entity.Device, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindPage", ctx, offset, limit)
	ret0, _ := ret[0].([]*entity.Device)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// FindPage indicates an expected call of FindPage.
func (mr *MockDeviceDAOMockRecorder) FindPage(ctx, offset, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindPage", reflect.TypeOf((*MockDeviceDAO)(nil).FindPage), ctx, offset, limit)
}

// Update mocks base method.
func (m *MockDeviceDAO) Update(ctx context.Context, device *entity.Device) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, device)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockDeviceDAOMockRecorder) Update(ctx, device any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockDeviceDAO)(nil).Update), ctx, device)
}
