// Code generated by MockGen. DO NOT EDIT.
// Source: internal/dao/interfaces/pcd_dao.go
//
// Generated by this command:
//
//	mockgen -source=internal/dao/interfaces/pcd_dao.go -destination=internal/testutil/mocks/mock_pcd_dao.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	entity "robot_scheduler/internal/model/entity"

	gomock "go.uber.org/mock/gomock"
)

// MockPCDFileDAO is a mock of PCDFileDAO interface.
type MockPCDFileDAO struct {
	ctrl     *gomock.Controller
	recorder *MockPCDFileDAOMockRecorder
	isgomock struct{}
}

// MockPCDFileDAOMockRecorder is the mock recorder for MockPCDFileDAO.
type MockPCDFileDAOMockRecorder struct {
	mock *MockPCDFileDAO
}

// NewMockPCDFileDAO creates a new mock instance.
func NewMockPCDFileDAO(ctrl *gomock.Controller) *MockPCDFileDAO {
	mock := &MockPCDFileDAO{ctrl: ctrl}
	mock.recorder = &MockPCDFileDAOMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPCDFileDAO) EXPECT() *MockPCDFileDAOMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockPCDFileDAO) Create(ctx context.Context, file *entity.PCDFile) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, file)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockPCDFileDAOMockRecorder) Create(ctx, file any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockPCDFileDAO)(nil).Create), ctx, file)
}

// Delete mocks base method.
func (m *MockPCDFileDAO) Delete(ctx context.Context, id uint) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockPCDFileDAOMockRecorder) Delete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockPCDFileDAO)(nil).Delete), ctx, id)
}

// FindAll mocks base method.
func (m *MockPCDFileDAO) FindAll(ctx context.Context) ([]*entity.PCDFile, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindAll", ctx)
	ret0, _ := ret[0].([]*entity.PCDFile)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindAll indicates an expected call of FindAll.
func (mr *MockPCDFileDAOMockRecorder) FindAll(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindAll", reflect.TypeOf((*MockPCDFileDAO)(nil).FindAll), ctx)
}

// FindByID mocks base method.
func (m *MockPCDFileDAO) FindByID(ctx context.Context, id uint) (*entity.PCDFile, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByID", ctx, id)
	ret0, _ := ret[0].(*entity.PCDFile)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByID indicates an expected call of FindByID.
func (mr *MockPCDFileDAOMockRecorder) FindByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByID", reflect.TypeOf((*MockPCDFileDAO)(nil).FindByID), ctx, id)
}

// FindByName mocks base method.
func (m *MockPCDFileDAO) FindByName(ctx context.Context, name string) (*entity.PCDFile, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByName", ctx, name)
	ret0, _ := ret[0].(*entity.PCDFile)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByName indicates an expected call of FindByName.
func (mr *MockPCDFileDAOMockRecorder) FindByName(ctx, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByName", reflect.TypeOf((*MockPCDFileDAO)(nil).FindByName), ctx, name)
}

// FindPage mocks base method.
func (m *MockPCDFileDAO) FindPage(ctx context.Context, offset, limit int) ([]*entity.PCDFile, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindPage", ctx, offset, limit)
	ret0, _ := ret[0].([]*entity.PCDFile)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// FindPage indicates an expected call of FindPage.
func (mr *MockPCDFileDAOMockRecorder) FindPage(ctx, offset, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindPage", reflect.TypeOf((*MockPCDFileDAO)(nil).FindPage), ctx, offset, limit)
}

// Update mocks base method.
func (m *MockPCDFileDAO) Update(ctx context.Context, file *entity.PCDFile) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, file)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockPCDFileDAOMockRecorder) Update(ctx, file any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockPCDFileDAO)(nil).Update), ctx, file)
}
